version: '3.8'

services:
  honeypot:
    build: .
    container_name: ssh-honeypot
    ports:
      # uncomment for VPS hosting
      # - "22:22"

      # uncomment for local testing (replace 2222 with localhost port)
      - "2222:22"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

    cap_drop:
      - ALL

    security_opt:
      - no-new-privileges:true

    read_only: true
