
"""
Reads an input JSON log file generated by the honeypot for offline analysis 
of collected attacker data. All data is output to terminal and written to CSV files.

Aggregates and sorts data by field:
 - Credentials          (top username/passwords and pairs)
 - Commands             (top commands, categorised by intention)
 - Source IP            (potential geolocation analysis)
 - Volume and timing    (connections per hour/day, attack periods)
"""

import sys
import json
import csv
from pathlib import Path
from collections import Counter

OUTPUT_DIR = Path("output")
OUTPUT_DIR.mkdir(exist_ok=True)

# writes a Counter object to a CSV file, sorted by frequency (desc)
def csv_write(filepath, counter):
    with open(filepath, "w", newline="") as f:
        writer = csv.writer(f)
        for i, count in counter.most_common():
            row = list(i) if isinstance(i, tuple) else [i]
            writer.writerow(row + [count])

def csv_write_raw(filepath, raw_entries):
    with open(filepath, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["timestamp", "type", "ip", "username", "password", "command"])
        writer.writerows(raw_entries)

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 aggregate.py <logfile>")
        sys.exit(1)

    logfile = Path(sys.argv[1])

    event_types = Counter()
    ips = Counter()
    usernames = Counter()
    passwords = Counter()
    credentials = Counter()
    commands = Counter()

    raw_entries = []

    with open(logfile, "r") as f:
        for line in f:
            event = json.loads(line)

            etype = event.get("type")
            event_types[etype] += 1

            ip = event.get("ip", "")
            username = event.get("username", "")
            password = event.get("password", "")
            command = event.get("command", "")

            if etype == "connection":
                ips[ip] += 1

            if etype == "login_attempt":
                credentials[(username, password)] += 1
                usernames[username] += 1
                passwords[password] += 1

            if etype in ("command", "exec_request"):
                commands[command] += 1


            raw_entries.append([event.get("timestamp", ""), etype, ip, username, password, command])

    # output results to terminal

    print("Event counts:")
    for t, count in event_types.most_common():
        print(f"    {t:<20} {count}")

    print("\nTop 5 IPs:")
    for ip, count in ips.most_common(5):
        print(f"    {ip:<20} {count}")

    print("\nTop 5 username:password pairs:")

    print(f"    {'Username':<15} {'Password':<20} {'Count'}")
    print("    " + "-" * 45)
    for (u, p), count in credentials.most_common(5):
        print(f"    {u:<15} {p:<20} {count}")

    print("\nTop 5 commands:")
    for c, count in commands.most_common(5):
        print("-" * 45)
        print(f"Count: {count}\n")
        print(c)

    print()


    # write to CSV files

    csv_write(OUTPUT_DIR / "ips.csv", ips)
    csv_write(OUTPUT_DIR / "credentials.csv", credentials)
    csv_write(OUTPUT_DIR / "usernames.csv", usernames)
    csv_write(OUTPUT_DIR / "passwords.csv", passwords)
    csv_write(OUTPUT_DIR / "commands.csv", commands)
    csv_write_raw(OUTPUT_DIR / "raw_events.csv", raw_entries)
    print("\nCSV files written in 'output' directory: \n    " \
          "ips.csv, credentials.csv, usernames.csv, passwords.csv, commands.csv, raw_events.csv")


if __name__ == "__main__":
    main()
